Fix wgetprogress() with --debian-installer (Closes: #829725)
The --debian-installer option caused wget's exit status in
wgetprogress() to be ignored, due to the pipeline.  Because
download_release_sig() first tries to download InRelease, this caused
release verification errors on archive mirrors without InRelease files.

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -80,8 +80,18 @@ wgetprogress () {
 	[ ! "$VERBOSE" ] && NVSWITCH="-nv"
 	local ret=0
 	if [ "$USE_DEBIANINSTALLER_INTERACTION" ] && [ "$PROGRESS_NEXT" ]; then
-		wget $@ 2>&1 >/dev/null | "$PKGDETAILS" "WGET%" "$PROGRESS_NOW" "$PROGRESS_NEXT" "$PROGRESS_END" >&3
-		ret=$?
+		# The exit status of a pipeline is that of the last command in
+		# the pipeline, so wget's exit status must be saved in the
+		# pipeline's first command.  Since commands in a pipeline run in
+		# subshells, we have to print the exit status (on a file
+		# descriptor other than standard output, which is used by the
+		# pipeline itself) and then assign it to $ret outside of the
+		# pipeline.  The "||" is necessary due to "set -e"; otherwise, a
+		# non-zero exit status would cause the echo command to be
+		# skipped.  If wget succeeds, $ret will be "", so it then has to
+		# be set to a default value of 0.
+		ret=$({ { wget $@ 2>&1 >/dev/null || echo $? >&2; } | "$PKGDETAILS" "WGET%" "$PROGRESS_NOW" "$PROGRESS_NEXT" "$PROGRESS_END" >&3; } 2>&1)
+		: ${ret:=0}
 	else
 		wget $NVSWITCH $@
 		ret=$?
